# config/config.yaml
app:
  name: "API Parametros generales"
  version: "1.0.0"
  debug: True
  port: 5003

database:
  tns_alias: "ORADESA"
  user: "mantencion"
  password: "m4ntenc10n_prod"
  min_pool_size: 2
  max_pool_size: 10
  increment: 1

logging:
  level: "DEBUG"
  file: "/var/log/api_parametro.log"
  max_size: "10MB"
  backup_count: 5
