gateway:
  name: "API - GATEWAY"
  verion : "1.0.0"
  port: 8001
  debug: True

service_mapping:
  credito: "http://192.168.120.8:5005"
  ahorro: "http://192.168.120.8:5006"
  parametro: "http://192.168.120.8:5000"

