/* Formatted on 2/12/2025 3:35:14 PM (QP5 v5.227.12220.39724) */
SELECT A.CREDITO AS NROCUENTA,
       P.DESCRIPCION AS TIPOCUENTA,
       A.CUOTAS AS NUMEROCUOTAS,
       A.MONTOLIQUIDO AS MONTOCREDITO,
       A.VALORCUOTA AS VALORCUOTA,
       TO_CHAR (CUO.FECHAVENCIMIENTO, 'DD-MM-YYYY') PROXVENCIMIENTO,
       A.CEDULA AS RUT
  FROM CREDITO.CREDITO A,
       CREDITO.PRODUCTO P,
       (  SELECT CREDITO, MIN (FECHAVENCIMIENTO) AS FECHAVENCIMIENTO
            FROM CREDITO.CUOTA
           WHERE ESTADO >= 0
        GROUP BY CREDITO) CUO
 WHERE A.CREDITO = CUO.CREDITO AND A.PRODUCTO = P.CODIGO AND A.CEDULA = :RUT