SELECT P.NOMBRE, C.SALDODISPONIBLE, C.SALDOCONTABLE, S.NOMBRE, C.FECHAAPERTURA, TO_NUMBER (
                        TRIM (C.CODIGOSISTEMA)
                     || TRIM (TO_CHAR (C.CODIGOSUCURSAL, '000'))
                     || TRIM (TO_CHAR (C.NUMEROCUENTA, '0000000'))
                     || TRIM (C.DIGITOCUENTA))
                     AS NROCUENTA FROM AHORRO.CUENTAAHORRO C, AHORRO.PRODUCTO P, SGT.SUCURSAL S WHERE C.CODIGOPRODUCTO = P.CODIGOPRODUCTO AND S.CODIGOSUCURSAL = C.CODIGOSUCURSAL AND RUTTITULAR1 = 10430012

