/*
nro cuenta
cupo autorizado
cupo utilizado
cupo disponible
rut
*/

SELECT LCC.CODIGO, LCC.CUPOOTORGADO AS CUPO_AUTORIZADO, LCC.CUPOUTILIZADO, LCC.MONTORETENIDO AS CUPO_DISPONIBLE
FROM LINEACC.LINEADECREDITO LCC WHERE RUTCLIENTE =: rut