SELECT * FROM (SELECT T.NOMBRE,
        M.MONTOMOVIMIENTO AS MONTO,
        TO_CHAR(M.FECHAHORA,'DD-MM-YYYY') AS FECHA,
        SUC.NOMBRE AS SUCURSAL,
        M.CREDITO AS CREDITO
FROM    CREDITO.MOVIMIENTODIARIO  M,
        CREDITO.TIPOMOVIMIENTO T,
        SGT.SUCURSAL SUC,
        CREDITO.CREDITO C
WHERE M.TIPOMOVIMIENTO = T.CODIGO
AND M.SUCURSAL = SUC.CODIGOSUCURSAL
AND M.CREDITO = C.CREDITO
AND C.CEDULA =:RUT
ORDER BY M.FECHAHORA DESC)
WHERE ROWNUM <= 25