/* original que busca movimientos mas recientes de hace 5 meses */
SELECT MOV.CODIGOSUCURSAL,
       MOV.MONTO,
       MOV.FECHAEFECTIVA,
       TRA.NOMBRE,
       TRA.NOMBREABREVIADO,
       TRA.CARGOABONO,
       SUC.NOMBRE, 
       TO_NUMBER (
                        TRIM (CTA.CODIGOSISTEMA)
                     || TRIM (TO_CHAR (CTA.CODIGOSUCURSAL, '000'))
                     || TRIM (TO_CHAR (CTA.NUMEROCUENTA, '0000000'))
                     || TRIM (CTA.DIGITOCUENTA)) AS NROCUENTA
  FROM AHORRO.MOVIMIENTOS MOV,
       AHORRO.TRANSACCION TRA,
       AHORRO.CUENTAAHORRO CTA,
       SGT.SUCURSAL SUC
 WHERE     MOV.CODIGOTRANSACCION = TRA.CODIGOTRANSACCION
       AND MOV.CODIGOSUCURSAL = SUC.CODIGOSUCURSAL
       AND MOV.NUMEROCUENTA = CTA.NUMEROCUENTA
       AND CTA.SUCURSALCONTABLE = SUC.CODIGOSUCURSAL
       AND CTA.RUTTITULAR1 = :RUT
       AND MOV.FECHAEFECTIVA >= ADD_MONTHS((SELECT MAX(FECHACONTABLE) FROM AHORRO.MOVIMIENTOS), -5)
       
  
 
 /*version limite con cantidad filas. fecha no es maxima*/
SELECT
       MOV.MONTO,
       TO_CHAR(MOV.FECHAEFECTIVA, 'DD-MM-YYYY'),
       TRA.NOMBRE,
       TRA.NOMBREABREVIADO,
       TRA.CARGOABONO,
       SUC.NOMBRE,
       TO_NUMBER (
                        TRIM (CTA.CODIGOSISTEMA)
                     || TRIM (TO_CHAR (CTA.CODIGOSUCURSAL, '000'))
                     || TRIM (TO_CHAR (CTA.NUMEROCUENTA, '0000000'))
                     || TRIM (CTA.DIGITOCUENTA)) AS NROCUENTA
  FROM AHORRO.MOVIMIENTOS MOV,
       AHORRO.TRANSACCION TRA,
       AHORRO.CUENTAAHORRO CTA,
       SGT.SUCURSAL SUC
 WHERE     MOV.CODIGOTRANSACCION = TRA.CODIGOTRANSACCION
       AND MOV.CODIGOSUCURSAL = SUC.CODIGOSUCURSAL
       AND MOV.NUMEROCUENTA = CTA.NUMEROCUENTA
       AND CTA.SUCURSALCONTABLE = SUC.CODIGOSUCURSAL
       AND CTA.RUTTITULAR1 = :RUT
       AND ROWNUM <= 15
       ORDER BY MOV.FECHAEFECTIVA DESC

/* version 2 con limites de columna y fecha max funcionandos*/
SELECT * FROM(
SELECT
       MOV.MONTO,
       TO_CHAR(MOV.FECHAEFECTIVA, 'DD-MM-YYYY'),
       TRA.NOMBRE,
       TRA.NOMBREABREVIADO,
       TRA.CARGOABONO,
       SUC.NOMBRE AS SUCURSAL,
       TO_NUMBER (
                        TRIM (CTA.CODIGOSISTEMA)
                     || TRIM (TO_CHAR (CTA.CODIGOSUCURSAL, '000'))
                     || TRIM (TO_CHAR (CTA.NUMEROCUENTA, '0000000'))
                     || TRIM (CTA.DIGITOCUENTA)) AS NROCUENTA
  FROM AHORRO.MOVIMIENTOS MOV,
       AHORRO.TRANSACCION TRA,
       AHORRO.CUENTAAHORRO CTA,
       SGT.SUCURSAL SUC
 WHERE     MOV.CODIGOTRANSACCION = TRA.CODIGOTRANSACCION
       AND MOV.CODIGOSUCURSAL = SUC.CODIGOSUCURSAL
       AND MOV.NUMEROCUENTA = CTA.NUMEROCUENTA
       AND CTA.SUCURSALCONTABLE = SUC.CODIGOSUCURSAL
       AND CTA.RUTTITULAR1 = :RUT
       ORDER BY MOV.FECHAEFECTIVA DESC)
WHERE ROWNUM <=25

/*20 movimientos mas recientes por cuenta*/
SELECT * FROM (
    SELECT
        MOV.MONTO,
        TO_CHAR(MOV.FECHAEFECTIVA, 'DD-MM-YYYY') AS FECHA,
        TRA.NOMBRE,
        TRA.NOMBREABREVIADO,
        TRA.CARGOABONO,
        SUC.NOMBRE AS SUCURSAL,
        TO_NUMBER (
            TRIM (CTA.CODIGOSISTEMA)
            || TRIM (TO_CHAR (CTA.CODIGOSUCURSAL, '000'))
            || TRIM (TO_CHAR (CTA.NUMEROCUENTA, '0000000'))
            || TRIM (CTA.DIGITOCUENTA)
        ) AS NROCUENTA,
        ROW_NUMBER() OVER (PARTITION BY CTA.NUMEROCUENTA ORDER BY MOV.FECHAEFECTIVA DESC) AS RN
    FROM AHORRO.MOVIMIENTOS MOV
    JOIN AHORRO.TRANSACCION TRA ON MOV.CODIGOTRANSACCION = TRA.CODIGOTRANSACCION
    JOIN AHORRO.CUENTAAHORRO CTA ON MOV.NUMEROCUENTA = CTA.NUMEROCUENTA
    JOIN SGT.SUCURSAL SUC ON MOV.CODIGOSUCURSAL = SUC.CODIGOSUCURSAL AND CTA.SUCURSALCONTABLE = SUC.CODIGOSUCURSAL
    WHERE CTA.RUTTITULAR1 = :RUT
) WHERE RN <= 20
