SELECT *
  FROM (  SELECT M.LINEADECREDITO AS OPERACION,
                 T.DESCRIPCION AS TIPOMOVIMIENTO,
                 TO_CHAR (M.FECHAREALIZACION, 'dd-mm-yyyy') AS FECHA,
                 S.NOMBRE AS SUCURSAL,
                 M.MONTOMOVIMIENTO AS MONTO
            FROM LINEACC.MOVIMIENTODIARIO M,
                 LINEACC.LINEADECREDITO C,
                 LINEACC.TIPOMOVIMIENTO T,
                 SGT.SUCURSAL S
           WHERE     M.TIPOMOVIMIENTO = T.CODIGO
                 AND M.SUCURSAL = S.CODIGOSUCURSAL
                 AND M.LINEADECREDITO = C.CODIGO
                 AND C.RUTCLIENTE = :rut
        ORDER BY M.FECHAREALIZACION DESC)
WHERE ROWNUM <= 20


/*
Muestra 20 de cada cuenta
SELECT * FROM (
    SELECT 
        M.LINEADECREDITO AS OPERACION,
        T.DESCRIPCION AS TIPOMOVIMIENTO,
        TO_CHAR(M.FECHAREALIZACION, 'dd-mm-yyyy') AS FECHA,
        S.NOMBRE AS SUCURSAL,
        M.MONTOMOVIMIENTO AS MONTO,
        ROW_NUMBER() OVER (PARTITION BY C.CODIGO ORDER BY M.FECHAREALIZACION DESC) AS RN
    FROM LINEACC.MOVIMIENTODIARIO M
    INNER JOIN LINEACC.LINEADECREDITO C ON M.LINEADECREDITO = C.CODIGO
    INNER JOIN LINEACC.TIPOMOVIMIENTO T ON M.TIPOMOVIMIENTO = T.CODIGO
    INNER JOIN SGT.SUCURSAL S ON M.SUCURSAL = S.CODIGOSUCURSAL
    WHERE C.RUTCLIENTE = :rut
) WHERE RN <= 20
*/