SELECT CS.CUENTA, TO_CHAR(CS.FECHAPAGO, 'DD-MM-YYYY'), CS.MONTO, TR.NOMBRE, TR.NOMBREABREVIADO, TR.ESCARGO
FROM CSOCIAL.MOVIMIENTO CS, CSOCIAL.TRANSACCION TR, CSOCIAL.CUENTA CTA
WHERE CS.CODIGOTRANSACCION  = TR.CODIGOTRANSACCION AND CTA.CUENTA = CS.CUENTA AND CTA.RUTTITULAR = :rut and CS.FECHAPAGO >= ADD_MONTHS((SELECT MAX(FECHAPAGO) FROM CSOCIAL.MOVIMIENTO), -5)

SELECT CS.CUENTA, TO_CHAR(CS.FECHAPAGO, 'DD-MM-YYYY'), CS.MONTO, TR.NOMBRE, TR.NOMBREABREVIADO, TR.ESCARGO, CTA.RUTTITULAR
FROM CSOCIAL.MOVIMIENTO CS, CSOCIAL.TRANSACCION TR, CSOCIAL.CUENTA CTA
WHERE CS.CODIGOTRANSACCION  = TR.CODIGOTRANSACCION AND CTA.CUENTA = CS.CUENTA and CS.FECHAPAGO >= ADD_MONTHS((SELECT MAX(FECHAPAGO) FROM CSOCIAL.MOVIMIENTO), -5) and TR.ESCARGO = 'S' AND CTA.ESTADO = 2

SELECT * FROM CLIENTE.CLAVEINTERNET WHERE RUTCLIENTE =: RUT

/* Formatted on 2/12/2025 2:44:13 PM (QP5 v5.227.12220.39724) */
  SELECT * FROM (SELECT CS.CUENTA,
         TO_CHAR(CS.FECHAPAGO,'DD-MM-YYYY'),
         CS.MONTO,
         TR.NOMBRE,
         TR.NOMBREABREVIADO,
         TR.ESCARGO,
         SUC.NOMBRE AS SUCURSAL
    FROM CSOCIAL.MOVIMIENTO CS,
         CSOCIAL.TRANSACCION TR,
         CSOCIAL.CUENTA CTA,
         SGT.SUCURSAL SUC
   WHERE     CS.CODIGOTRANSACCION = TR.CODIGOTRANSACCION
         AND CTA.CUENTA = CS.CUENTA
         AND CTA.CODIGOSUCURSAL = SUC.CODIGOSUCURSAL
         AND CTA.RUTTITULAR = :rut
   ORDER BY CS.FECHAPAGO DESC)
   WHERE ROWNUM <=25
